{% set name = "doxygen" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.gz
  url: http://doxygen.nl/files/{{ name }}-{{ version }}.src.tar.gz
  sha256: 75cd0ac7df462d3b730d8fe76d879c7e8395f930f88a6270aa63adf3cec3737d

  patches:
    # CMake finds iconv_open in glibc, but finds iconv.h from libiconv.
    # Make sure both are found from one place.
    - find_iconv.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - cmake
    - flex  # [not win]
    - libxml2  # [win]  # xmllint.exe used for testing inside building step
    - m4  # [not win]
    - make  # [not win]
    - miktex  # [win]  # used for testing inside building step
    - ninja  # [win]
    - python
    - texlive-core  # [not win]
    - winflexbison  # [win]
    - m2-diffutils  # [win]  # diff.exe used for testing inside building step
    - m2-libiconv  # [win]  # undeclared dependency of m2-diffutils
    - m2-libintl  # [win]  # undeclared dependency of m2-diffutils
    - perl  # [win]  # perl.exe is used for testing inside building step
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - doxygen --help

about:
  home: http://www.stack.nl/~dimitri/doxygen/index.html
  license: GPL2
  license_file: LICENSE
  summary: Generate documentation from source code

  description: |
    Doxygen is the de facto standard tool for
    generating documentation from annotated C++ sources,
    but it also supports other popular programming
    languages such as C, Objective-C, C#, PHP, Java,
    Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors),
    Fortran, VHDL, Tcl, and to some extent D.
  doc_url: http://www.stack.nl/~dimitri/doxygen/manual/index.html
  dev_url: https://github.com/doxygen/doxygen

extra:
  recipe-maintainers:
    - bluescarni
    - isuruf
    - tadeu
