{% set name = "doxygen" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/Release_{{ version | replace(".", "_") }}.tar.gz
  sha256: 5ca35e1258020df5fe8b21c3656aed156c317def4a81b7fe52f452edc9f35768

  patches:
    - fix_osx.diff
    # https://github.com/doxygen/doxygen/issues/10055
    - macos.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - cmake
    - flex  # [not win]
    - libxml2  # [win]  # xmllint.exe used for testing inside building step
    - m4  # [not win]
    - make  # [not win]
    # - miktex  # [win]  # used for testing inside building step
    - ninja  # [win]
    - python
    - texlive-core  # [not win]
    - winflexbison  # [win]
    - m2-diffutils  # [win]  # diff.exe used for testing inside building step
    - m2-libiconv  # [win]  # undeclared dependency of m2-diffutils
    - m2-libintl  # [win]  # undeclared dependency of m2-diffutils
    - perl  # [win]  # perl.exe is used for testing inside building step
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - doxygen --version | grep {{ version }}  # [not win]
    - doxyapp --version | grep {{ version }}  # [not win]
    - doxygen --version  # [win]
    - doxyapp --version  # [win]

about:
  home: https://www.doxygen.nl/index.html
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Generate documentation from source code

  description: |
    Doxygen is the de facto standard tool for
    generating documentation from annotated C++ sources,
    but it also supports other popular programming
    languages such as C, Objective-C, C#, PHP, Java,
    Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors),
    Fortran, VHDL, Tcl, and to some extent D.
  doc_url: https://www.doxygen.nl/manual/index.html
  dev_url: https://github.com/doxygen/doxygen

extra:
  recipe-maintainers:
    - bluescarni
    - isuruf
    - tadeu
    - tdegeus
